# Generated by Django 4.1.7 on 2023-11-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dureePreparation', models.DateField()),
                ('image_url', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
