# Generated by Django 4.1.7 on 2023-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettecuisine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
