# Generated by Django 4.1.7 on 2023-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettecuisine', '0002_alter_recette_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
