# Generated by Django 4.1.7 on 2023-11-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettecuisine', '0003_alter_recette_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='dureePreparation',
            field=models.DateTimeField(),
        ),
    ]
