# Generated by Django 4.1.7 on 2023-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettecuisine', '0005_recette_etapepreparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='etapePreparation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
