# Generated by Django 4.1.7 on 2023-11-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettecuisine', '0006_alter_recette_etapepreparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='dureePreparation',
            field=models.IntegerField(),
        ),
    ]
